import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import { authOptions } from "@/lib/auth-options";
import { getServerSession } from "next-auth";
import Nav from "@/components/Nav";
import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="tr" className="light">
      <head>
        <link rel="icon" type="image/svg+xml" href="/berber-favicon.svg" />
      </head>
      <body className={`${inter.variable} ${robotoMono.variable}`} style={{background:'#faf5ff'}}>
        <Providers session={session}>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
